"""Analytics endpoints — dashboard overview, sales trends, product/store analysis.

Reads from pre-aggregated compact CSVs (data/processed/analytics_*.csv) instead
of the full engineered_features.csv, which is hundreds of MB and too slow to
load on every request. The aggregate files are regenerated by
backend/scripts/regenerate_analytics_aggregates.py.
"""

import json

import pandas as pd

from fastapi import APIRouter, HTTPException, Depends

from app.core.dependencies import get_current_user
from app.schemas.analytics import (
    OverviewMetrics, SalesTrendPoint, TopProduct, StorePerformance,
    SeasonalBreakdown, DayOfWeekAnalysis,
)
from app.models.user import User

router = APIRouter()

PROCESSED = "data/processed"
META_FILE = f"{PROCESSED}/analytics_meta.json"
DAILY_FILE = f"{PROCESSED}/analytics_daily.csv"
PRODUCTS_FILE = f"{PROCESSED}/analytics_products.csv"

# Module-level caches so we parse each small aggregate once, not per request.
_cache = {"daily": None, "products": None, "meta": None}


def _load_daily() -> pd.DataFrame:
    """Daily store-level sales (date, store_id, total_sales, item_count)."""
    if _cache["daily"] is None:
        try:
            _cache["daily"] = pd.read_csv(DAILY_FILE)
            _cache["daily"]["date"] = pd.to_datetime(_cache["daily"]["date"])
        except FileNotFoundError:
            raise HTTPException(status_code=404, detail="No processed data found")
    return _cache["daily"]


def _load_products() -> pd.DataFrame:
    """Per-product totals (item_id, total_sales, days_sold, store_count)."""
    if _cache["products"] is None:
        try:
            _cache["products"] = pd.read_csv(PRODUCTS_FILE)
        except FileNotFoundError:
            raise HTTPException(status_code=404, detail="No processed data found")
    return _cache["products"]


def _load_meta() -> dict:
    """Overview metadata (totals computed at aggregation time)."""
    if _cache["meta"] is None:
        try:
            with open(META_FILE) as f:
                _cache["meta"] = json.load(f)
        except FileNotFoundError:
            raise HTTPException(status_code=404, detail="No processed data found")
    return _cache["meta"]


@router.get("/overview")
async def get_overview(current_user: User = Depends(get_current_user)):
    """Get dashboard overview metrics."""
    m = _load_meta()
    return OverviewMetrics(
        total_products=int(m["total_products"]),
        total_stores=int(m["total_stores"]),
        total_categories=int(m["total_categories"]),
        total_states=int(m["total_states"]),
        total_sales=float(m["total_sales"]),
        avg_daily_sales=float(m["avg_daily_sales"]),
        date_range=m["date_range"],
        n_time_series=int(m["n_time_series"]),
    )


@router.get("/sales-trend")
async def get_sales_trend(
    days: int = 90,
    current_user: User = Depends(get_current_user),
):
    """Get sales trend data for the last N days (daily totals across stores)."""
    daily = _load_daily()
    by_day = daily.groupby("date")["total_sales"].sum().reset_index().sort_values("date")
    if len(by_day) > days:
        by_day = by_day.tail(days)

    return [
        SalesTrendPoint(date=row["date"].date(), sales=float(row["total_sales"]))
        for _, row in by_day.iterrows()
    ]


@router.get("/top-products")
async def get_top_products(
    limit: int = 10,
    current_user: User = Depends(get_current_user),
):
    """Get top-selling products."""
    prods = _load_products().sort_values("total_sales", ascending=False).head(limit)
    return [
        TopProduct(
            item_id=row["item_id"],
            total_sales=float(row["total_sales"]),
            avg_daily_sales=float(row["total_sales"] / row["days_sold"]) if row["days_sold"] else 0.0,
            store_count=int(row["store_count"]),
        )
        for _, row in prods.iterrows()
    ]


@router.get("/store-performance")
async def get_store_performance(current_user: User = Depends(get_current_user)):
    """Get store performance comparison."""
    daily = _load_daily()
    stores = daily.groupby("store_id").agg(
        total_sales=("total_sales", "sum"),
        days=("date", "nunique"),
        item_count=("item_count", "max"),
    ).sort_values("total_sales", ascending=False)

    return [
        StorePerformance(
            store_id=idx,
            total_sales=float(row["total_sales"]),
            avg_daily_sales=float(row["total_sales"] / row["days"]) if row["days"] else 0.0,
            item_count=int(row["item_count"]),
        )
        for idx, row in stores.iterrows()
    ]


@router.get("/seasonal")
async def get_seasonal_breakdown(current_user: User = Depends(get_current_user)):
    """Get sales breakdown by season."""
    from app.services.weather_service import WeatherService

    daily = _load_daily().copy()
    daily["season"] = daily["date"].apply(WeatherService.get_season)
    seasonal = daily.groupby("season").agg(
        total_sales=("total_sales", "sum"),
        days=("date", "nunique"),
    ).reset_index()

    return [
        SeasonalBreakdown(
            season=row["season"],
            avg_sales=float(row["total_sales"] / row["days"]) if row["days"] else 0.0,
            total_sales=float(row["total_sales"]),
            item_count=0,  # not tracked at store-day aggregate level
        )
        for _, row in seasonal.iterrows()
    ]


@router.get("/day-of-week")
async def get_day_of_week_analysis(current_user: User = Depends(get_current_user)):
    """Get sales analysis by day of week."""
    days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    daily = _load_daily().copy()
    daily["dow"] = daily["date"].dt.dayofweek
    dow_avg = daily.groupby("dow")["total_sales"].mean()
    peak = dow_avg.max()

    return [
        DayOfWeekAnalysis(
            day=days[int(idx)],
            avg_sales=float(row),
            pct_of_peak=float((row / peak) * 100) if peak > 0 else 0,
        )
        for idx, row in dow_avg.items()
    ]
